{% set name = "cmweather" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmweather-{{ version }}.tar.gz
  sha256: 298f18d67fbf807bfb1dca7df267f37757068c4db90373a3a1671e3831a2beee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.6
    - numpy
    - matplotlib-base

test:
  imports:
    - cmweather
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openradar/cmweather
  summary: A library of useful colormaps when visualizing weather and climate data, with numerous color vision deficiency friendly options
  dev_url: https://github.com/openradar/cmweather
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgrover1
    - zssherman
